version: '3.1'
services:
  tiffanyblue:
    ports:
      - "18890:1323"
    image: eosdaq/tiffanyblue
    container_name: eos_tiffany
    networks:
      - eos_net
    depends_on:
      - eos_db
    links:
      - eos_db
    environment:
      - DB_HOST=eos_db
      - DB_PORT=3306
      - DB_NAME=eosdaq
      - DB_USER=eosdaquser
      - DB_PASS=eosdaqvotmdnjem
      - ENV=devel
      - AWS_ON=false
  burgundy:
    ports:
      - "18889:1313"
    image: eosdaq/burgundy
    container_name: eos_burgundy
    networks:
      - eos_net
    depends_on:
      - eos_db
    links:
      - eos_db
    environment:
      - EOSDAQMANAGE=${EOSDAQMANAGE}
      - EOS_HOST=http://local_nodeos
      - EOS_PORT=8888
      - DB_HOST=eos_db
      - DB_USER=eosdaquser
      - DB_PASS=eosdaqvotmdnjem
      - ENV=devel
  eos_db:
    ports:
      - "3306:3306"
    image: mariadb
    container_name: eos_db
    networks:
      - eos_net
    environment:
        MYSQL_ROOT_PASSWORD: eosdaqvotmdnjem
        MYSQL_DATABASE: eosdaq
        MYSQL_USER: eosdaquser
        MYSQL_PASSWORD: eosdaqvotmdnjem
networks:
  eos_net:
      external: true

