version: '3.1'
services:
  burgundy:
    ports:
      - "18889:1313"
    image: eosdaq/burgundy
    networks:
      - eos_net
    deploy:
      replicas: 1
    depends_on:
      - eos_db
    environment:
      - EOSDAQ_EOSDAQOOOO2O=${EOSDAQ_EOSDAQOOOO2O}
      - EOSDAQ_EOSDAQMANAGE=${EOSDAQ_EOSDAQMANAGE}
      - EOSDAQ_EOS_HOST=http://local_eosio
      - EOSDAQ_EOS_PORT=8888
      - EOSDAQ_DB_HOST=eos_db
      - EOSDAQ_DB_USER=eosdaquser
      - EOSDAQ_DB_PASS=eosdaqvotmdnjem
  db:
    ports:
      - "3306:3306"
    image: mariadb
    networks:
      - eos_net
    environment:
        MYSQL_ROOT_PASSWORD: eosdaqvotmdnjem
        MYSQL_DATABASE: eosdaq
        MYSQL_USER: eosdaquser
        MYSQL_PASSWORD: eosdaqvotmdnjem
networks:
  eos_net:
      external: true

